version: '3'
services:
  nginx:
    build: ./proxy
    networks:
        - mynet
        - global
    restart: on-failure
    ports:
        - "80"
  app:
    build: ./app
    ports:
        - "3000"
    networks:
        - mynet
    restart: on-failure
networks: 
    mynet:
    global:
        external: true